### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [knot126/KnShim#1]
it crashes even if i follow the steps

**Comment by H-A-M-G-E-R** [comment]
i built libshim.so, put it aside libsmashhit.so, and i replaced "smashhit" to "shim", but it still crashes

**Comment by knot126** [comment]
how exactly is it failing?

**Comment by knot126** [comment]
Realised I forgot to note the need to patch libsmashhit.so to remove anti-tamper to the install instructions. Try doing that, it should work then.

**Comment by H-A-M-G-E-R** [comment]
changed the package name, still fails even if antitamper is patched out

**Comment by H-A-M-G-E-R** [comment]
also no releases are published

**Comment by H-A-M-G-E-R** [comment]
i want this to give each boss a different theme song instead of having the same theme

**Comment by knot126** [comment]
I've put up the binaries from the SHL Discord, but I'm not sure why it would be failing otherwise. Are there any other mods you've made to the APK which might cause issues ?

**Comment by H-A-M-G-E-R** [comment]
Used the release on github, it finally works!
